name: Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sed Config Base
        shell: bash
        run: |
          sed -i  "s#VITE_BUILD_COMPRESS\s*=.*#VITE_BUILD_COMPRESS = 'gzip'#g" ./apps/admin/.env.production
          sed -i  "s#VITE_DROP_CONSOLE\s*=.*#VITE_DROP_CONSOLE = true#g" ./apps/admin/.env.production
          cat ./apps/admin/.env.production

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set SSH Environment
        env:
          DOCS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTIONS_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com > ~/.ssh/known_hosts
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
          git config --global user.email "ruixijiejie@gmail.com"
          git config --global user.name "lucifer"

      - name: Build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build -t turbo-demo:latest -f apps/admin/Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        run: docker push turbo-demo:latest

      - name: SSH into Deployment Server
        uses: appleboy/ssh-action@master
        with:
          host: 60.205.181.203
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop turbo-demo || true
            docker rm turbo-demo || true
            docker pull turbo-demo:latest
            docker run -d --name turbo-demo -p 80:80 turbo-demo:latest
