name: Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build -t turbo-demo:latest -f apps/admin/Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        run: docker push turbo-demo:latest

      - name: SSH into Deployment Server
        uses: appleboy/ssh-action@master
        with:
          host: 60.205.181.203
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop turbo-demo || true
            docker rm turbo-demo || true
            docker pull turbo-demo:latest
            docker run -d --name turbo-demo -p 80:80 turbo-demo:latest
